{%- from "kubernetes/map.jinja" import common with context -%}
{%- from "kubernetes/map.jinja" import master with context -%}
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-kube-manager
  namespace: {{ common.addons.contrail_network_controller.get('namespace', 'kube-system') }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  contrail.conf: |
    [DEFAULT]
    master = localhost:8080
    service-cluster-ip-range = {{ master.service_addresses }}

    [opencontrail]
    default-domain = {{ master.network.opencontrail.get('default_domain', 'default-domain') }}
    public-ip-range = {{ master.network.opencontrail.get('public_ip_range', '185.22.97.128/26') }}
    cluster-service = {{ master.network.opencontrail.get('cluster_service', 'kube-system/default') }}
    api-server = {{ master.network.opencontrail.config.api.host }}
    api-port = {{ master.network.opencontrail.get('port', 8082) }}
    default = {{ master.network.opencontrail.get('default_project', 'default-domain:default-project') }}
    public-network = {{ master.network.opencontrail.get('public_network', 'default-domain:default-project:Public') }}
    private-ip-range = {{ master.network.opencontrail.private_ip_range }}
    network-label = {{ master.network.opencontrail.get('network_label', 'opencontrail.org/name') }}
    service-label = {{ master.network.opencontrail.get('service_label', 'opencontrail.org/uses') }}
    service-cluster-ip-range = {{ master.get('service_addresses', '10.254.0.0/16') }}
