{%- from "kubernetes/map.jinja" import common with context -%}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: 'Heapster'
    addonmanager.kubernetes.io/mode: Reconcile
  name: heapster-address
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
  externalIPs: ['{{ common.addons.heapster_influxdb.public_ip }}']
  type: LoadBalancer
