{%- from "kubernetes/map.jinja" import master with context -%}
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    version: v6
    addonmanager.kubernetes.io/mode: Reconcile
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
#        name: heapster
        uses: monitoring-influxdb
        k8s-app: heapster
        version: v6
        kubernetes.io/cluster-service: "true"
    spec:
      {%- if 'RBAC' in master.auth.get('mode', "") %}
      serviceAccountName: heapster
      {%- endif %}
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
