{%- from "kubernetes/map.jinja" import master with context %}
{%- from "kubernetes/map.jinja" import common with context %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netchecker-server
  namespace: {{ common.addons.netchecker.namespace }}
  labels:
    app: netchecker-agent
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netchecker-server
        addonmanager.kubernetes.io/mode: Reconcile
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ common.addons.netchecker.port }}"
{%- if common.addons.netchecker.cni is defined %}
        cni: {{ common.addons.netchecker.cni }}
{%- endif %}
    spec:
      serviceAccountName: netchecker
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: netchecker-server
          image: {{ common.addons.netchecker.server_image }}
          ports:
            - containerPort: {{ common.addons.netchecker.port }}
          args:
            - "-v=5"
            - "-logtostderr"
            - "-endpoint=0.0.0.0:{{ common.addons.netchecker.port }}"
{%- if common.addons.get('contrail_network_controller', {}).get('enabled') %}
            - "-kubeproxyinit=true"
{%- else %}
            - "-kubeproxyinit=false"
            - "-etcd-endpoints={% for member in master.etcd.members %}https://{{ member.host }}:4001{% if not loop.last %},{% endif %}{% endfor %}"
{%- if master.etcd.get('ssl', {}).get('enabled') %}
            - "-etcd-key=/var/lib/etcd/etcd-client.key"
            - "-etcd-cert=/var/lib/etcd/etcd-client.pem"
            - "-etcd-ca=/var/lib/etcd/ca.pem"
{%- endif %}
          volumeMounts:
          - mountPath: /var/lib/etcd/
            name: etcd-certs
            readOnly: true
      volumes:
      - hostPath:
          path: /var/lib/etcd
        name: etcd-certs
{%- endif %}
