{%- from "kubernetes/map.jinja" import common with context -%}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: netchecker-agent
  namespace: {{ common.addons.netchecker.namespace }}
  labels:
    app: netchecker-agent
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      name: netchecker-agent
      labels:
        app: netchecker-agent
      annotations:
{%- if common.addons.netchecker.cni is defined %}
        cni: {{ common.addons.netchecker.cni }}
{%- endif %}
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: netchecker-agent
          image: {{ common.addons.netchecker.agent_image }}
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "-v=5"
            - "-alsologtostderr=true"
            - "-serverendpoint=netchecker:{{ common.addons.netchecker.port }}"
            - "-reportinterval={{ common.addons.netchecker.interval }}"
{%- if common.addons.netchecker.get('agent_probeurls') %}
            - "-probeurls={{ common.addons.netchecker.agent_probeurls }}"
{%- endif %}
