apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-manager
  namespace: kube-system
  labels:
    app: kube-manager
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-manager
  template:
    metadata:
      labels:
        app: kube-manager
    spec:
      hostNetwork: true
      containers:
      - name: opencontrail-kube-manager
        image: docker-prod-local.artifactory.mirantis.com/opencontrail-oc40/opencontrail-kube-manager
        securityContext:
          privileged: true
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - >
                apt update;
                apt install python-eventlet;
                service contrail-kube-manager restart;


        volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-contrail
          mountPath: /etc/contrail

      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
          type: Directory
      - name: etc-contrail
        hostPath:
          path: /etc/contrail
          type: Directory

      nodeSelector:
        "node-role.kubernetes.io/master": "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
